apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kuryrnetworks.openstack.org
spec:
  group: openstack.org
  scope: Namespaced
  version: v1
  names:
    plural: kuryrnetworks
    singular: kuryrnetwork
    kind: KuryrNetwork
    shortNames:
      - kns
  versions:
          #- name: v1
          #served: true
          #storage: true
  additionalPrinterColumns:
      - name: SUBNET-CIDR
        type: string
        description: The subnet CIDR allocated to the namespace
        JSONPath: .status.subnetCIDR
      - name: Age
        type: date
        JSONPath: .metadata.creationTimestamp

        #schema:
  validation:      
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - nsName
            - projectId
            - nsLabels
            properties:
              nsName:
                type: string
              projectId:
                type: string
              nsLabels:
                x-kubernetes-preserve-unknown-fields: true
                type: object
          status:
            type: object
            properties:
              netId:
                type: string
              populated:
                type: boolean
              routerId:
                type: string
              subnetCIDR:
                type: string
              subnetId:
                type: string
              nsLabels:
                x-kubernetes-preserve-unknown-fields: true
                type: object
